version: '3'
services:
  mysql-standalone:
    image: mysql:8
    networks: 
     - usecase
    environment:
     - MYSQL_ROOT_PASSWORD=admin
     - MYSQL_DATABASE=salesdb
    volumes: 
     - ./init:/docker-entrypoint-initdb.d
     - ./mysql_data:/var/lib/mysql
    ports:
     - '3306:3306'
    expose:
     - '3306'
    healthcheck:
      interval: 120s
      timeout: 120s
      retries: 5
  
  springboot:
    restart: on-failure
    build: ./
    expose:
     - "8080"
    ports:
     - 8085:8080
    networks: 
     - usecase
    environment:
     - WAIT_HOSTS=mysql-standalone:3306
    depends_on:
     - mysql-standalone

networks:
 usecase:
